spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.142.141:3307/sell?characterEncoding=utf-8&useSSL=false  # 如果不是 SSL 协议会报警告。关闭警告。
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

server:
  context-path: /sell
